
PLUGIN_NAME	= alsa
PLUGIN_FAMILY	= device/sound
PLUGIN_LIBS	= -lasound
PLUGIN_SOURCES	= sound_alsa.cxx

PREFIX=PTLIBDIR=/home/tool/opal/ptlib-2.10.11_arm
exec_prefix = ${PREFIX}
export LIBDIR=${exec_prefix}/lib_linux_arm
export PTLIBDIR=/home/tool/opal/ptlib-2.10.11_arm

include ../../make/plugins.mak
